name: washify_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Design
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  another_flutter_splash_screen: ^1.2.1
  flutter_gutter: ^2.2.0
  lottie: ^2.2.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  flutter_smart_dialog: ^4.9.8+5
  cool_alert: ^2.0.1
  dotted_line: ^3.2.3

  # Helpers
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  dartz: ^0.10.1

  # Network
  intl: ^0.20.0
  internet_connection_checker_plus: ^2.5.2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  pretty_dio_logger: ^1.4.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/fonts/
     - assets/images/
     - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800


